# Generated by Django 3.2.9 on 2021-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_auto_20211119_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.CharField(blank=True, help_text='Give a Short Description of Restaurant', max_length=500),
        ),
    ]
