# Generated by Django 3.2.9 on 2021-11-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_auto_20211119_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Restaurant Open Currently'),
        ),
    ]
