# Generated by Django 3.2.9 on 2021-11-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_menu_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is Restaurant Open Currently'),
        ),
    ]
