# Generated by Django 3.2.9 on 2021-11-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_auto_20211119_0005'),
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='vote',
            name='restaurant_menu',
            field=models.ForeignKey(help_text='Relation with Restaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurantapp.menu'),
        ),
    ]
